In [1]:
import numpy as np

In [21]:
a = np.empty( (3,3) )
a

array([[ 1.14285714, -2.28571429,  0.57142857],
       [-2.28571429,  4.97142857, -1.54285714],
       [ 0.57142857, -1.54285714,  0.88571429]])

In [26]:
a = np.append(a, [[4,5,6]], axis=0)
a[3,:]

array([4., 5., 6.])

In [32]:
a = np.array([4.0, 6 , 7 ,8 ,8])
b = np.logical_and(6 <= a, a <= 15)
a[b]


array([6., 7., 8., 8.])

In [33]:
rng = np.random.default_rng()

In [49]:
rng.integers(2)

1